package API;

public class AndroidApi {	
/*	android.accessibilityservice
	android.accounts
	android.animation
	android.annotation
	android.app
	android.app.admin
	android.app.assist
	android.app.backup
	android.app.job
	android.app.usage
	android.appwidget
	android.bluetooth
	android.bluetooth.le
	android.content
	android.content.pm
	android.content.res
	android.database
	android.database.sqlite
	android.databinding
	android.drm
	android.gesture
	android.graphics
	android.graphics.drawable
	android.graphics.drawable.shapes
	android.graphics.pdf
	android.hardware
	android.hardware.camera2
	android.hardware.camera2.params
	android.hardware.display
	android.hardware.fingerprint
	android.hardware.input
	android.hardware.usb
	android.inputmethodservice
	android.location
	android.media
	android.media.audiofx
	android.media.browse
	android.media.effect
	android.media.midi
	android.media.projection
	android.media.session
	android.media.tv
	android.mtp
	android.net
	android.net.http
	android.net.nsd
	android.net.rtp
	android.net.sip
	android.net.wifi
	android.net.wifi.p2p
	android.net.wifi.p2p.nsd
	android.nfc
	android.nfc.cardemulation
	android.nfc.tech
	android.opengl
	android.os
	android.os.storage
	android.preference
	android.print
	android.print.pdf
	android.printservice
	android.provider
	android.renderscript
	android.sax
	android.security
	android.security.keystore
	android.service.carrier
	android.service.chooser
	android.service.dreams
	android.service.media
	android.service.notification
	android.service.restrictions
	android.service.textservice
	android.service.voice
	android.service.wallpaper
	android.speech
	android.speech.tts
	android.support.annotation
	android.support.app.recommendation
	android.support.customtabs
	android.support.design
	android.support.design.widget
	android.support.multidex
	android.support.percent
	android.support.v13.app
	android.support.v14.preference
	android.support.v17.leanback
	android.support.v17.leanback.app
	android.support.v17.leanback.database
	android.support.v17.leanback.graphics
	android.support.v17.leanback.system
	android.support.v17.leanback.widget
	android.support.v17.preference
	android.support.v4.accessibilityservice
	android.support.v4.animation
	android.support.v4.app
	android.support.v4.content
	android.support.v4.content.pm
	android.support.v4.content.res
	android.support.v4.database
	android.support.v4.graphics
	android.support.v4.graphics.drawable
	android.support.v4.hardware.display
	android.support.v4.hardware.fingerprint
	android.support.v4.media
	android.support.v4.media.session
	android.support.v4.net
	android.support.v4.os
	android.support.v4.print
	android.support.v4.provider
	android.support.v4.text
	android.support.v4.util
	android.support.v4.view
	android.support.v4.view.accessibility
	android.support.v4.view.animation
	android.support.v4.widget
	android.support.v7.app
	android.support.v7.appcompat
	android.support.v7.cardview
	android.support.v7.graphics
	android.support.v7.graphics.drawable
	android.support.v7.gridlayout
	android.support.v7.media
	android.support.v7.mediarouter
	android.support.v7.preference
	android.support.v7.recyclerview
	android.support.v7.util
	android.support.v7.view
	android.support.v7.widget
	android.support.v7.widget.helper
	android.support.v7.widget.util
	android.support.v8.renderscript
	android.system
	android.telecom
	android.telephony
	android.telephony.cdma
	android.telephony.gsm
	android.test
	android.test.mock
	android.test.suitebuilder
	android.test.suitebuilder.annotation
	android.text
	android.text.format
	android.text.method
	android.text.style
	android.text.util
	android.transition
	android.util
	android.view
	android.view.accessibility
	android.view.animation
	android.view.inputmethod
	android.view.textservice
	android.webkit
	android.widget
	java.net
*/
	//156ÐÐ
}
